### PR TITLE
Added ignore_dirs setting

### PR DESCRIPTION
**Pull request by jsimnz**
Added feature #19

Can now add paths to ignore watching

### CODE REVIEW

**Comment by begizi** [comment]
:+1: Much needed option.

**Comment by boonep** [comment]
It looks like this and several other pull requests were declined because commas in filenames aren't supported.  What format is preferred for a list of directories @pilu?  Perhaps pipe separation?

i.e.
ignore_dirs: dir1 | dir2 | dir3

**Comment by metal3d** [comment]
Why not a yaml file ? That could be easier to write:

```yaml
ignore_dirs:
- dir1
- dir2
- dir3
```

And the entire configuration could be in yaml file.

That's what I'm using with my own framework (github.com/kwiscale) - at this time, I'm unable to use angular because of the "node_modules" and "bower_components" directory... :(

**Comment by pilu** [comment]
@metal3d yes I think yml would be a good idea if someone one to implement it.

**Comment by drKnoxy** [comment]
👍

**Comment by gmccue** [comment]
Fixed by #60

**Pull request closed without merging**
